-- CreateEnum
CREATE TYPE "ReviewLevel" AS ENUM ('MANAGER', 'PARTNER', 'QUALITY_CONTROL');

-- CreateEnum
CREATE TYPE "ManagerReviewStatus" AS ENUM ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'APPROVED', 'REJECTED', 'REQUIRES_CHANGES');

-- CreateEnum
CREATE TYPE "FinalizationStatus" AS ENUM ('DRAFT', 'IN_PROGRESS', 'REVIEW', 'APPROVED', 'FINALIZED', 'ISSUED');

-- CreateEnum
CREATE TYPE "OpinionType" AS ENUM ('UNQUALIFIED', 'QUALIFIED', 'ADVERSE', 'DISCLAIMER');
