/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Main tutorial sidebar
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '👋 Welcome',
    },
    {
      type: 'category',
      label: '📚 Understanding the Basics',
      collapsed: false,
      items: [
        'basics/what-is-auditing',
        'basics/audit-terminology',
        'basics/system-overview',
        'basics/why-cloudaudit-pro',
      ],
    },
    {
      type: 'category',
      label: '👥 Meet the Team - User Roles',
      collapsed: true,
      items: [
              {
                type: 'autogenerated',
                dirName: 'basics',
              },
        'actors/senior-auditor',
        'actors/auditor',
        'actors/intern',
        'actors/client',
      ],
    },
    {
              {
                type: 'autogenerated',
                dirName: 'actors',
              },
        'processes/04-execution',
        'processes/05-review',
        'processes/06-reporting',
        'processes/07-completion',
      ],
    },
    {
              'processes/audit-lifecycle',
              'processes/company-setup',
              'processes/engagement-planning',
              'processes/risk-assessment',
              'processes/interim-testing',
              'processes/year-end-fieldwork',
              'processes/review-quality-control',
              'processes/finalization-reporting',
              'processes/client-communication',
            'modules/company/overview',
            'modules/company/setup',

          items: [
