/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '👋 Welcome',
    },
    {
      type: 'category',
      label: '📚 Understanding the Basics',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'basics',
        },
      ],
    },
    {
      type: 'category',
      label: '👥 Meet the Team - User Roles',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'actors',
        },
      ],
    },
    {
      type: 'category',
      label: '🔄 The Audit Journey - Business Processes',
      collapsed: true,
      items: [
        'processes/audit-lifecycle',
        'processes/company-setup',
        'processes/engagement-planning',
        'processes/risk-assessment',
        'processes/interim-testing',
        'processes/year-end-fieldwork',
        'processes/review-quality-control',
        'processes/finalization-reporting',
        'processes/client-communication',
      ],
    },
    {
      type: 'category',
      label: '🧩 Product Modules',
      collapsed: true,
      items: [
        'modules/index',
        'modules/company/overview',
        'modules/team',
        'modules/periods',
        'modules/chart-of-accounts',
        'modules/documents/overview',
        'modules/procedures/overview',
        'modules/workpapers/overview',
        'modules/reporting/overview',
      ],
    },
    {
      type: 'category',
      label: '🧪 Examples',
      collapsed: true,
      items: ['examples/overview', 'examples/scenarios/year-end-audit'],
    },
    {
      type: 'category',
      label: '📖 Reference',
      collapsed: true,
      items: ['reference/glossary', 'reference/quick-guides/overview'],
    },
    {
      type: 'category',
      label: '🛡️ Platform',
      collapsed: true,
      items: ['security/overview', 'api/index', 'performance/monitoring'],
    },
  ],
};

module.exports = sidebars;
