export enum ReportType {
  TRIAL_BALANCE = 'TRIAL_BALANCE',
  GENERAL_LEDGER = 'GENERAL_LEDGER',
  FINANCIAL_STATEMENT = 'FINANCIAL_STATEMENT',
  AUDIT_WORKPAPER = 'AUDIT_WORKPAPER',
  AUDIT_SUMMARY = 'AUDIT_SUMMARY',
  FIXED_ASSET = 'FIXED_ASSET',
  LIABILITY_REPORT = 'LIABILITY_REPORT',
  BANK_RECONCILIATION = 'BANK_RECONCILIATION',
  COMPLIANCE_REPORT = 'COMPLIANCE_REPORT',
  DASHBOARD = 'DASHBOARD',
  ANALYTICS = 'ANALYTICS',
  CUSTOM = 'CUSTOM',
}

export enum ReportCategory {
  FINANCIAL = 'FINANCIAL',
  OPERATIONAL = 'OPERATIONAL',
  COMPLIANCE = 'COMPLIANCE',
  AUDIT_WORKPAPER = 'AUDIT_WORKPAPER',
  MANAGEMENT = 'MANAGEMENT',
  CLIENT_DELIVERABLE = 'CLIENT_DELIVERABLE',
}

export enum ReportStatus {
  QUEUED = 'QUEUED',
  GENERATING = 'GENERATING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum ExportFormat {
  PDF = 'PDF',
  EXCEL = 'EXCEL',
  CSV = 'CSV',
  JSON = 'JSON',
  HTML = 'HTML',
  WORD = 'WORD',
}
